version: '3.9'
services:

  app:                                                          # Название сервиса
    container_name: mongorilla_app                              # Название контейнера
    build: .                                                    # Образ контейнера берем из текущей папки
    ports:                                                      # Связываем порты хоста:контейнера
      - 8080:8080 
    restart: on-failure
    volumes:                                                    # Монтируем том с приложением
      - api:/usr/src/app/
    depends_on:                                                 # Ставим в зависимость от БД
      - mongo
    networks:                                                   # Подключаем к сети
      - mongorilla_network


  mongo:                                                        # Название сервиса
    image: mongo:latest                                         # Название:версия образа (mongo:latest)
    container_name: mongorilla_mongo                            # Название контейнера
    restart: always
    ports:                                                      # Связываем порты хоста:контейнера
      - 27017:27017
    environment:                                                # Прокидываем переменные окружения
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
    # volumes:                                                    # Монтируем тома с данными БД
    #   - mongo-data:/data/db/                                    
    #   - mongo-log:/var/log.mongodb/
    networks:                                                   # Подключаем к сети
      - mongorilla_network


  mongo-express:                                                # Название сервиса
    image: mongo-express:latest                                 # Название:версия образа (mongo-express:latest)
    container_name: mongorilla_express                          # Название контейнера
    restart: always
    ports:                                                      # Связываем порты хоста:контейнера
      - 8081:8081                 
    environment:                                                # Прокидываем переменные окружения
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_EXPRESS_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_EXPRESS_PASSWORD}
      ME_CONFIG_MONGODB_URL: mongodb://xander:rndm-pass@mongo:27017/
    depends_on:                                                 # Ставим в зависимость от БД
      - mongo
    networks:                                                   # Подключаем к сети
      - mongorilla_network

# Список томов
volumes:
  api:
#   mongo-data:
#   mongo-log:


# Настройки сети (чтоб контейнеры могли обмениваться данными)
networks:
  mongorilla_network:
    driver: bridge